coreutils: Fix make check
Change-Id: I65e7d657f0ad2b24f17e4bc8f8178612fe8773f5
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/11745
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Tapas Kundu <tkundu@vmware.com>

diff --git a/SPECS/coreutils/make-check-failure.patch b/SPECS/coreutils/make-check-failure.patch
--- a/SPECS/coreutils/make-check-failure.patch
+++ b/SPECS/coreutils/make-check-failure.patch
@@ -1,32 +1,56 @@
-diff --git a/tests/df/df-symlink.sh b/tests/df/df-symlink.sh
-index 4047256..e7d7477 100755
---- a/tests/df/df-symlink.sh
-+++ b/tests/df/df-symlink.sh
-@@ -34,10 +34,10 @@ compare exp out || fail=1
- # I.e., '.' => /dev/mapper/fedora-home -> /dev/dm-2
- # Restrict this test to systems with a 1:1 mapping between
- # source and target.  This excludes for example BTRFS sub-volumes.
--if test "$(df --output=source | grep -F "$disk" | wc -l)" = 1; then
--  df --out=source,target '.' > out || fail=1
--  compare exp out || fail=1
--fi
-+#if test "$(df --output=source | grep -F "$disk" | wc -l)" = 1; then
-+#  df --out=source,target '.' > out || fail=1
-+#  compare exp out || fail=1
-+#fi
+From c0e5f8c59b951ae13ca9cb9945cd77163489e1d9 Mon Sep 17 00:00:00 2001
+From: Bernhard Voelker <mail@bernhard-voelker.de>
+Date: Fri, 31 Jul 2020 19:49:35 +0200
+Subject: [PATCH] tests: skip some parts of 'tests/rmdir/ignore.sh' if run as
+ root
+
+Parts of this test expect that the rmdir syscall returns with EPERM,
+but the root user does not see that.
+
+* tests/rmdir/ignore.sh: Add uid_is_privileged_ guards around parts
+of the test which expect rmdir() to fail with EPERM.
+
+Reported by Nick Alcock <nix@esperi.org.uk> in
+https://bugs.gnu.org/42633
+---
+ tests/rmdir/ignore.sh | 19 +++++++++++++------
+ 1 file changed, 13 insertions(+), 6 deletions(-)
+
+diff --git a/tests/rmdir/ignore.sh b/tests/rmdir/ignore.sh
+index 65e92d012..b26ac533a 100755
+--- a/tests/rmdir/ignore.sh
++++ b/tests/rmdir/ignore.sh
+@@ -33,17 +33,24 @@ test -d "$cwd/a/b/c" && fail=1
+ # Between 6.11 and 8.31, the following rmdir would mistakenly succeed.
+ mkdir -p x/y || framework_failure_
+ chmod a-w x || framework_failure_
+-returns_ 1 rmdir --ignore-fail-on-non-empty x/y || fail=1
++
++if ! uid_is_privileged_; then  # root does not get EPERM.
++  returns_ 1 rmdir --ignore-fail-on-non-empty x/y || fail=1
++fi
++
+ test -d x/y || fail=1
+ # Between 6.11 and 8.31, the following rmdir would mistakenly fail,
+ # and also give a non descript error
+ touch x/y/z || framework_failure_
+ rmdir --ignore-fail-on-non-empty x/y || fail=1
+ test -d x/y || fail=1
+-# assume empty dir if unreadable entries (so failure to remove diagnosed)
+-rm x/y/z || framework_failure_
+-chmod a-r x/y || framework_failure_
+-returns_ 1 rmdir --ignore-fail-on-non-empty x/y || fail=1
+-test -d x/y || fail=1
++
++if ! uid_is_privileged_; then  # root does not get EPERM.
++  # assume empty dir if unreadable entries (so failure to remove diagnosed)
++  rm x/y/z || framework_failure_
++  chmod a-r x/y || framework_failure_
++  returns_ 1 rmdir --ignore-fail-on-non-empty x/y || fail=1
++  test -d x/y || fail=1
++fi
  
- test "$fail" = 1 && dump_mount_list_
- 
-diff --git a/tests/misc/help-version.sh b/tests/misc/help-version.sh
-index 46a518a..6d46832 100755
---- a/tests/misc/help-version.sh
-+++ b/tests/misc/help-version.sh
-@@ -184,7 +184,7 @@ defid_setup () { args=t; }
- basename_setup () { args=$tmp_in; }
- dirname_setup () { args=$tmp_in; }
- expr_setup () { args=foo; }
--
-+hostid_setup () { args=--version;}
- # Punt, in case GNU 'id' hasn't been installed yet.
- groups_setup () { args=--version; }
- 
+ Exit $fail
+-- 
+2.27.0
+
