rpm-ostree: Fixes rpm database bind mount
- Added /usr/share/empty for bind mount rpm
  database
- Add summary file in base tree required for
  `rpm-ostree upgrade` command.

Change-Id: I7ab8d36da377ba06a63e2cae27a0b6f5334cda43
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/19840
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Piyush Gupta <gpiyush@vmware.com>

diff --git a/SPECS/rpm-ostree/mkostreerepo b/SPECS/rpm-ostree/mkostreerepo
--- a/SPECS/rpm-ostree/mkostreerepo
+++ b/SPECS/rpm-ostree/mkostreerepo
@@ -159,6 +159,12 @@ function do-commit()
     exit $rc
   fi
   umask $UMASKVAL
+  ostree summary --repo=$REPODATAPATH --update
+  if [ "$rc" -ne 0 ]; then
+    echo "ERROR: ostree summary failed !!"
+    exit $rc
+  fi
+  ostree summary -v --repo=$REPODATAPATH
 }
 
 function create-base-tree()
