kpatch-util: Artifacts signing for GoBuilds
- Add "sign" argument in livepatch scripts
- GoBuilds environment provides signing script along with
  libraries used. We bind-mount these locations in Photon
  container.
- GB infra is permitted for a specific user. Hence, we
  add that user in container.
- sign_livepatch stored in internal github.

Change-Id: I2e592f57e379e90491694bd296d301a356625852
Signed-off-by: Kuntal Nayak <kuntal.nayak@broadcom.com>
Reviewed-on: http://photon-gerrit.lvn.broadcom.net/c/photon/+/25983
Reviewed-by: gerrit-photon <svc.photon-ci@broadcom.com>
Reviewed-by: Brennan Lamoreaux <brennan.lamoreaux@broadcom.com>
Tested-by: gerrit-photon <svc.photon-ci@broadcom.com>
Reviewed-by: Guruswamy Basavaiah <guruswamy.basavaiah@broadcom.com>

diff --git a/SPECS/kpatch/utils/auto_livepatch b/SPECS/kpatch/utils/auto_livepatch
--- a/SPECS/kpatch/utils/auto_livepatch
+++ b/SPECS/kpatch/utils/auto_livepatch
@@ -23,6 +23,13 @@ DESC_GIVEN=0
 RPM_DESC_GIVEN=0
 SRC_RPM_LOCAL_PATH=""
 DEBUGINFO_LOCAL_PATH=""
+SIGNC=""
+SIGNC_UID=0
+SIGNC_UNAME=""
+TMP_DIR=/tmp
+BLD_DIR=/build
+BLDLIB_DIR=/bldmnt
+AUTH_DIR=/etc/signing
 
 DOCKERFILE_DIR=${DOCKERFILE_DIR:-/usr/share/livepatch/dockerfiles/}
 DOCKER_KPATCH_BUILDLOG=/root/.kpatch/build.log
@@ -49,8 +56,8 @@ parse_args() {
 
     mkdir -p "$PATCHES_DIR"
     local opt=""
-    local options=( "-s" "-v" "-p" "-o" "-h" "--help" "-k" "-n" "-R" "--export-debuginfo" "-d" "--rpm" "--rpm-version" "--rpm-release" "--rpm-desc" "--verbose" )
-    local no_arg_options=( "-R" "--export-debuginfo" "-h" "--help" "--rpm" "--verbose")
+    local options=( "-s" "-v" "-p" "-o" "-h" "--help" "-k" "-n" "-R" "--export-debuginfo" "-d" "--rpm" "--rpm-version" "--rpm-release" "--rpm-desc" "--verbose" "--sign" )
+    local no_arg_options=( "-R" "--export-debuginfo" "-h" "--help" "--rpm" "--verbose" "--sign" )
 
     while (( "$#" )); do
         arg=$1
@@ -62,6 +69,11 @@ parse_args() {
                 print_help 0
             elif [[ $1 == --export-debuginfo ]]; then
                 EXPORT_DEBUGINFO=1
+            elif [[ $1 == --sign ]]; then
+                SIGNC=sign_livepatch
+                [[ -f "$SIGNC" ]] || error "Signc does not exist in the system: $SIGNC"
+                SIGNC_UID=$(id -u)
+                SIGNC_UNAME="$(id -u -n)"
             elif ! is_in_array "$opt" ${no_arg_options[*]} && [[ ($2 == -* || -z $2) ]]; then
                 error "$1 needs at least one argument"
             elif  [[ $3 != -* && $opt != -p && -n $3 ]] && ! is_in_array "$opt" ${no_arg_options[*]} ; then
@@ -118,6 +130,7 @@ parse_args() {
     [[ -n "$DEBUGINFO_LOCAL_PATH" ]] && ARGS="$ARGS -v $GEN_LIVEPATCH_WORKSPACE/$(basename "$DEBUGINFO_LOCAL_PATH")"
     [[ $DESC_GIVEN -eq 1 ]] && ARGS="$ARGS -d $GEN_LIVEPATCH_WORKSPACE/description.txt"
     [[ $RPM_DESC_GIVEN -eq 1 ]] && ARGS="$ARGS --rpm-desc $GEN_LIVEPATCH_WORKSPACE/rpm-description.txt"
+    [[ -n "$SIGNC" ]] && ARGS="$ARGS --signer-id $SIGNC_UID --signer-name $SIGNC_UNAME"
 
     ARGS="$ARGS -o ${DOCKER_LIVEPATCH_OUTPUT_DIR}"
 
@@ -137,6 +150,7 @@ config_container() {
     DOCKER_IMAGE_NAME=livepatch-$PH_TAG
     DOCKER_CONTAINER_NAME=$PH_TAG-livepatch-container
     DOCKERFILE_NAME=Dockerfile.$PH_TAG
+    local signc_mnts=()
     check_dockerfile
 
     if [[ -n "$(docker ps -a -f "name=$DOCKER_CONTAINER_NAME" -q 2> /dev/null)" ]]; then
@@ -145,10 +159,16 @@ config_container() {
         echo "Deleted Docker container from the previous run."
     fi
     $DOCKER rmi -f "$DOCKER_IMAGE_NAME" > /dev/null
+    [[ -n "$SIGNC" ]] && signc_mnts+=(
+        -v "$TMP_DIR":"$TMP_DIR"
+        -v "$AUTH_DIR":"$AUTH_DIR"
+        -v "$BLD_DIR":"$BLD_DIR"
+        -v "$BLDLIB_DIR":"$BLDLIB_DIR"
+    )
 
     echo -e "Building Docker image. This may take a few minutes.\n"
     $DOCKER buildx build --network=host -f $DOCKERFILE_DIR/"$DOCKERFILE_NAME" -t "$DOCKER_IMAGE_NAME" . > /dev/null || error "Failed to create Livepatch docker image."
-    $DOCKER run --network=host -t -d --name "$DOCKER_CONTAINER_NAME" "$DOCKER_IMAGE_NAME" /bin/bash > /dev/null || error "Creation of docker container failed"
+    $DOCKER run "${signc_mnts[@]}" -t -d --name "$DOCKER_CONTAINER_NAME" "$DOCKER_IMAGE_NAME" /bin/bash > /dev/null || error "Creation of docker container failed"
 
     # copy all necessary files into docker container, put patches into patches folder
     $DOCKER cp $PATCHES_DIR "$DOCKER_CONTAINER_NAME":$GEN_LIVEPATCH_WORKSPACE/ || error "Failed to copy patch files to docker container."
@@ -163,6 +183,9 @@ config_container() {
     fi
     if [[ -n "$DEBUGINFO_LOCAL_PATH" ]]; then
        $DOCKER cp "$DEBUGINFO_LOCAL_PATH" "$DOCKER_CONTAINER_NAME":$GEN_LIVEPATCH_WORKSPACE/ || error "Failed to copy kernel debuginfo rpm to docker container."
+    fi
+    if [[ -n "$SIGNC" ]]; then
+       $DOCKER cp "$SIGNC" "$DOCKER_CONTAINER_NAME":/usr/bin || error "Failed to copy sign_livepatch script."
     fi
 }
 
diff --git a/SPECS/kpatch/utils/gen_livepatch b/SPECS/kpatch/utils/gen_livepatch
--- a/SPECS/kpatch/utils/gen_livepatch
+++ b/SPECS/kpatch/utils/gen_livepatch
@@ -39,6 +39,9 @@ RPM_NAME=""
 BUILD_RPM_SPECFILE="/usr/share/livepatch/livepatch_spec.template"
 patches=()
 DEBUG_LOGS=0
+SIGNC=""
+SIGNC_UID=0
+SIGNC_UNAME=""
 
 # parse the command line arguments and fill in variables
 module_name_string() {
@@ -55,8 +58,8 @@ parse_args() {
     fi
 
     local opt=""
-    local options=( "-s" "-p" "-v" "-o" "-h" "--help" "-k" "-n" "-R" "--export-debuginfo" "-d" "--rpm" "--rpm-version" "--rpm-release" "--rpm-desc" "--verbose" )
-    local no_arg_options=( "-R" "--export-debuginfo" "-h" "--help" "--rpm" "--verbose" )
+    local options=( "-s" "-p" "-v" "-o" "-h" "--help" "-k" "-n" "-R" "--export-debuginfo" "-d" "--rpm" "--rpm-version" "--rpm-release" "--rpm-desc" "--verbose" "--sign" "--signer-id" "--signer-name" )
+    local no_arg_options=( "-R" "--export-debuginfo" "-h" "--help" "--rpm" "--verbose" "--sign" )
     while (( "$#" )); do
         if [[ $1 = -* ]]; then
             opt=$1
@@ -74,6 +77,9 @@ parse_args() {
                 PACKAGE_AS_RPM=1
             elif [[ $1 == --verbose ]]; then
                 DEBUG_LOGS=1
+            elif [[ $1 == --sign ]]; then
+                SIGNC="/usr/bin/sign_livepatch"
+                [[ -f "$SIGNC" ]] || error "Signc does not exist in the system: $SIGNC"
             elif ! is_in_array "$opt" ${no_arg_options[*]} && [[ $2 == -* || -z $2 ]]; then
                 error "$1 needs at least one argument"
             elif  [[ $3 != -* && $opt != -p && -n $3 ]] && ! is_in_array "$opt" ${no_arg_options[*]} ; then
@@ -119,6 +125,12 @@ parse_args() {
                     [ -f "$RPM_DESCFILE" ] || error "RPM description file does not exist"
                     RPM_DESCFILE=$(readlink -f "$RPM_DESCFILE")
                     ;;
+                --signer-id)
+                    SIGNC_UID=$1
+                    ;;
+                --signer-name)
+                    SIGNC_UNAME=$1
+                    ;;
                 esac
         fi
         # shift to the next argument
@@ -139,6 +151,7 @@ parse_args() {
     get_kernel_version "$VERSION_RELEASE_FLAVOR"
     get_kernel_release "$VERSION_RELEASE_FLAVOR"
     get_photon_tag "$VERSION_RELEASE_FLAVOR"
+    [[ -n "$SIGNC" ]] && config_sign_user
 
     if [[ "$PH_TAG" != *ph* ]]; then
         echo "Wrong kernel version detected: $KERNEL_VERSION_RELEASE"
@@ -181,6 +194,11 @@ parse_args() {
 
     # make sure output folder exists
     mkdir -p "$OUTPUT_FOLDER"
+}
+
+config_sign_user() {
+    echo "Adding user uid=$SIGNC_UID($SIGNC_UNAME) for signing."
+    useradd -u $SIGNC_UID $SIGNC_UNAME 2>/dev/null || error "Cannot add signing user."
 }
 
 # takes in uname -r formatted string
@@ -423,6 +441,12 @@ package_module_in_rpm() {
 
     cp "$OUTPUT_FOLDER"/"$LIVEPATCH_NAME".ko "$TEMP_DIR"/rpmbuild/SOURCES || error
 
+    local signc_args=()
+    [[ -n "$SIGNC" ]] && signc_args+=(
+        --define "%signing_script %(echo $SIGNC)"
+        --define "%signing_user %(echo $SIGNC_UNAME)"
+    )
+
     # fill in needed info in spec file skeleton
     local spec_file="$TEMP_DIR/rpmbuild/SPECS/livepatch.spec"
     cp "$BUILD_RPM_SPECFILE" "$spec_file" || error
@@ -443,7 +467,7 @@ package_module_in_rpm() {
     echo "* $(date "+%a %b %d %Y") Auto Livepatch $RPM_VERSION-$RPM_RELEASE" >> "$spec_file"
     echo "- Auto Livepatch version $RPM_VERSION-$RPM_RELEASE built">> "$spec_file"
     echo "Building rpm"
-    rpmbuild -ba $spec_file --define "$rpmdir" --define "%dist .$PH_TAG" &> $GENLOGS_DIR/rpmbuild-livepatch-pkg.log
+    rpmbuild -ba $spec_file "${signc_args[@]}" --define "$rpmdir" --define "%dist .$PH_TAG" &> $GENLOGS_DIR/rpmbuild-livepatch-pkg.log
     status=$?
     [[ $DEBUG_LOGS -eq 1 ]] && cat "$GENLOGS_DIR"/rpmbuild-livepatch-pkg.log
     [[ $status -ne 0 ]] && error "Packaging kernel module as rpm failed"
@@ -452,6 +476,11 @@ package_module_in_rpm() {
     cp "$TEMP_DIR"/rpmbuild/RPMS/*/"$RPM_NAME"*.rpm "$OUTPUT_FOLDER" || error "Current dir: $(pwd). Failed to save RPM to $OUTPUT_FOLDER"
 
     echo "SUCCESS: Building rpm finished"
+
+    if [ -n "$SIGNC" ]; then
+        echo "Signing RPM now."
+        find "$OUTPUT_FOLDER" -type f -name "*.rpm" -exec "$SIGNC" -t rpm -u "$SIGNC_UNAME" -a {} \; || error "Signing livepatch RPM failed!"
+    fi
 }
 
 cleanup() {
