kpatch-utils: Fix find-exec issue where error from signing script is not thrown
Change-Id: Ib2f4f49cf6844e3bd20d72bbc304ef018d8e4eec
Signed-off-by: Kuntal Nayak <kuntal.nayak@broadcom.com>
Reviewed-on: http://photon-gerrit.lvn.broadcom.net/c/photon/+/26163
Tested-by: gerrit-photon <svc.photon-ci@broadcom.com>
Reviewed-by: Brennan Lamoreaux <brennan.lamoreaux@broadcom.com>

diff --git a/SPECS/kpatch/utils/gen_livepatch b/SPECS/kpatch/utils/gen_livepatch
--- a/SPECS/kpatch/utils/gen_livepatch
+++ b/SPECS/kpatch/utils/gen_livepatch
@@ -479,8 +479,9 @@ build_and_package_kpatch_module() {
     cp "$TEMP_DIR"/rpmbuild/BUILD/"$LIVEPATCH_NAME".ko "$OUTPUT_FOLDER"  || error "Current dir: $(pwd). Failed to save ko file to $OUTPUT_FOLDER"
 
     if [ -n "$SIGNC" ]; then
-        echo "Signing RPM now."
-        find "$OUTPUT_FOLDER" -type f -name "*.rpm" -exec "$SIGNC" -t rpm -u "$SIGNC_UNAME" -a {} \; || error "Signing livepatch RPM failed!"
+        while IFS= read -r -d '' file; do
+            "$SIGNC" -t rpm -u "$SIGNC_UNAME" -a "$file" || error "Signing livepatch RPM failed!"
+        done < <(find "$OUTPUT_FOLDER" -type f -name "*.rpm" -print0)
     fi
     echo "SUCCESS: Building rpm finished"
 }
