Generate livepatch debug rpm
- Generate livepatch debug rpm
- Fixed upstream kpatch-build to build livepatch using kernel source rpm

Change-Id: Ia02c286ba20738a51ca542be82bc1ed58f482251
Signed-off-by: Guruswamy Basavaiah <guruswamy.basavaiah@broadcom.com>
Reviewed-on: http://photon-gerrit.lvn.broadcom.net/c/photon/+/26012
Reviewed-by: Shreenidhi Shedi <shreenidhi.shedi@broadcom.com>
Tested-by: gerrit-photon <svc.photon-ci@broadcom.com>
Reviewed-by: Brennan Lamoreaux <brennan.lamoreaux@broadcom.com>

diff --git a/SPECS/kpatch/utils/gen_livepatch b/SPECS/kpatch/utils/gen_livepatch
--- a/SPECS/kpatch/utils/gen_livepatch
+++ b/SPECS/kpatch/utils/gen_livepatch
@@ -18,7 +18,7 @@ RPM_BUILD_DIR="$TEMP_DIR/rpmbuild/BUILD"
 VERSION_RELEASE_FLAVOR=""
 LIVEPATCH_NAME=""
 DEBUG_PKGNAME=""
-SRC_PKGNAME=""
+KERNEL_SRC_RPM=""
 SPEC_FILENAME=""
 VMLINUX_PATH=""
 PH_TAG=""
@@ -26,15 +26,15 @@ KERNEL_RELEASE=""
 KERNEL_FLAVOR=""
 KERNEL_VERSION=""
 IS_RT=0
-NON_REPLACE_FLAG=""
+NON_REPLACE_FLAG=0
 EXPORT_DEBUGINFO=0
-DEBUGINFO_DIR="$BUILD_DIR/debuginfo"
+DEBUGINFO_DIR=""
 GENLOGS_DIR=""
 DESC_FILE=""
 RPM_DESCFILE=""
 PACKAGE_AS_RPM=0
-RPM_VERSION=0
-RPM_RELEASE=0
+RPM_VERSION=
+RPM_RELEASE=
 RPM_NAME=""
 BUILD_RPM_SPECFILE="/usr/share/livepatch/livepatch_spec.template"
 patches=()
@@ -70,7 +70,7 @@ parse_args() {
             elif [[ $1 == -h || $1 == --help ]]; then
                 print_help 0
             elif [[ $1 == -R ]]; then
-                NON_REPLACE_FLAG="-R"
+                NON_REPLACE_FLAG=1
             elif [[ $1 == --export-debuginfo ]]; then
                 EXPORT_DEBUGINFO=1
             elif [[ $1 == --rpm ]]; then
@@ -159,20 +159,16 @@ parse_args() {
         exit 1
     fi
 
+    [[ -z $RPM_VERSION ]] && RPM_VERSION=${KERNEL_VERSION}r${KERNEL_RELEASE}
+    [[ -z $RPM_RELEASE ]] && RPM_RELEASE=0
+
     if [[ -z "$LIVEPATCH_NAME" ]]; then
-        if [[ $PACKAGE_AS_RPM -eq 1 ]]; then
-            LIVEPATCH_NAME="linux-livepatch-"${VERSION_RELEASE_FLAVOR}-${RPM_VERSION}.${RPM_RELEASE}
-            RPM_NAME="linux-livepatch-"${VERSION_RELEASE_FLAVOR}
-        else
-            LIVEPATCH_NAME="linux-livepatch-"${VERSION_RELEASE_FLAVOR}
-        fi
+        LIVEPATCH_NAME="linux-livepatch"
     elif [[ "${LIVEPATCH_NAME##*.}" == "ko" ]]; then
         LIVEPATCH_NAME="${LIVEPATCH_NAME%.*}"
-        RPM_NAME=${LIVEPATCH_NAME}
-    else
-        RPM_NAME=${LIVEPATCH_NAME}
     fi
-    RPM_NAME=$(echo ${RPM_NAME} | cut -c 1-55)
+    RPM_NAME="$LIVEPATCH_NAME"
+    [[ $PACKAGE_AS_RPM -eq 1 ]] && LIVEPATCH_NAME="${LIVEPATCH_NAME}-${RPM_VERSION}-${RPM_RELEASE}"
     LIVEPATCH_NAME="$(module_name_string "$LIVEPATCH_NAME")"
     echo "Livepatch module name: $LIVEPATCH_NAME"
 
@@ -180,11 +176,12 @@ parse_args() {
         echo "Output folder not specified, using default."
         OUTPUT_FOLDER="$DEFAULT_OUTPUT_FOLDER"
     fi
+    DEBUGINFO_DIR="$OUTPUT_FOLDER"/debuginfo
+
     echo "Outputting livepatches to: $OUTPUT_FOLDER"
     GENLOGS_DIR="$OUTPUT_FOLDER/logs/"
     mkdir -p $GENLOGS_DIR
     GENLOGS_DIR=$(readlink -f "$GENLOGS_DIR")
-
 
     # if building an rpm, and rpm description is not specified, use the kernel module desc file if it is set
     if [[ -n "$DESC_FILE" && $PACKAGE_AS_RPM -eq 1 && -z "$RPM_DESCFILE" ]]; then
@@ -259,6 +256,23 @@ get_photon_tag() {
     PH_TAG=$kernel_tag
 }
 
+# vmlinux path is set when we parse the debuginfo package
+set_kernel_package_paths() {
+    #determine which photon version this is
+    PHOTON_VERSION="${PH_TAG//[^0-9]/}".0
+
+    #set file paths based on kernel flavor
+    if [[ "$KERNEL_FLAVOR" == "generic" ]]; then
+        DEBUG_PKGNAME="linux-debuginfo-$VERSION_RELEASE_FLAVOR.x86_64.rpm"
+        KERNEL_SRC_RPM="linux-$VERSION_RELEASE_FLAVOR.src.rpm"
+        SPEC_FILENAME="linux.spec"
+    else
+        DEBUG_PKGNAME="linux-$KERNEL_FLAVOR-debuginfo-$VERSION_RELEASE_FLAVOR.x86_64.rpm"
+        KERNEL_SRC_RPM="linux-$KERNEL_FLAVOR-$VERSION_RELEASE_FLAVOR.src.rpm"
+        SPEC_FILENAME="linux-$KERNEL_FLAVOR.spec"
+    fi
+}
+
 print_config() {
     echo -e "\nBuilding livepatch"
     echo -e "Linux Version: $VERSION_RELEASE_FLAVOR"
@@ -317,35 +331,6 @@ install_kernel_dependencies() {
     tdnf install -qy "${to_be_installed_pkgs[@]}" || error "Error installing required packages"
 }
 
-extract_source_rpm() {
-    echo -e "\nDownloading and/or processing source rpm, This will take a few minutes.\n"
-    local src_rpm_url="https://packages.vmware.com/photon/${PHOTON_VERSION}/photon_srpms_${PHOTON_VERSION}_x86_64/$SRC_PKGNAME"
-
-    # allow downloading/copying of source rpm from either local or custom urls. Just need these variables to be exported before
-    # running to enable these options.
-    if [ -n "${SRC_RPM_LOCAL_PATH}" ]; then
-        cp "$SRC_RPM_LOCAL_PATH" "$SRC_PKGNAME" || error "Couldn't find local src rpm"
-    else
-        if ! wget --quiet --show-progress "$src_rpm_url" ; then
-            error "Couldn't download photon kernel source rpm"
-        fi
-    fi
-
-    # set up temporary rpm build environment
-    local rpmdir="%_topdir %(echo $PWD)/rpmbuild"
-    mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} || error
-
-    rpm -i "$SRC_PKGNAME" --define "$rpmdir" || error "Failed to extract spec file"
-
-    install_kernel_dependencies "$SRC_PKGNAME"
-
-    rpmbuild -bp "rpmbuild/SPECS/$SPEC_FILENAME" --define "$rpmdir" --define "%dist .$PH_TAG" &> $GENLOGS_DIR/rpmbuild-source-rpm-extract.log
-    status=$?
-    [[ $DEBUG_LOGS -eq 1 ]] && cat "$GENLOGS_DIR"/rpmbuild-source-rpm-extract.log
-    [[ $status -ne 0 ]] && error "Failed to extract kernel source and create linux source directory"
-
-}
-
 parse_debuginfo_rpm() {
     echo -e "\nDownloading debug package and extracting vmlinux"
 
@@ -364,123 +349,141 @@ parse_debuginfo_rpm() {
 
     # extract vmlinux
     rpm2cpio "$DEBUG_PKGNAME" | cpio -ivd "./$VMLINUX_PATH"  > /dev/null || error "Couldn't extract vmlinux from $DEBUG_PKGNAME"
+    cp "./$VMLINUX_PATH" "$TEMP_DIR"/rpmbuild/SOURCES/
 }
 
-# vmlinux path is set when we parse the debuginfo package
-set_kernel_package_paths() {
-    #determine which photon version this is
-    PHOTON_VERSION="${PH_TAG//[^0-9]/}".0
+download_source_rpm() {
+    echo -e "\nDownloading source rpm, This will take a few minutes.\n"
+    local src_rpm_url="https://packages.vmware.com/photon/${PHOTON_VERSION}/photon_srpms_${PHOTON_VERSION}_x86_64/$KERNEL_SRC_RPM"
 
-    #set file paths based on kernel flavor
-    if [[ "$KERNEL_FLAVOR" == "generic" ]]; then
-        DEBUG_PKGNAME="linux-debuginfo-$VERSION_RELEASE_FLAVOR.x86_64.rpm"
-        SRC_PKGNAME="linux-$VERSION_RELEASE_FLAVOR.src.rpm"
-        SPEC_FILENAME="linux.spec"
+    # allow downloading/copying of source rpm from either local or custom urls. Just need these variables to be exported before
+    # running to enable these options.
+    local KERNEL_SRC_RPM_PATH="$TEMP_DIR"/rpmbuild/SOURCES/"$KERNEL_SRC_RPM"
+    if [ -n "${SRC_RPM_LOCAL_PATH}" ]; then
+        cp "$SRC_RPM_LOCAL_PATH" "$KERNEL_SRC_RPM_PATH" || error "Couldn't find local src rpm"
     else
-        DEBUG_PKGNAME="linux-$KERNEL_FLAVOR-debuginfo-$VERSION_RELEASE_FLAVOR.x86_64.rpm"
-        SRC_PKGNAME="linux-$KERNEL_FLAVOR-$VERSION_RELEASE_FLAVOR.src.rpm"
-        SPEC_FILENAME="linux-$KERNEL_FLAVOR.spec"
+        if ! wget --quiet --show-progress "$src_rpm_url" -O "$KERNEL_SRC_RPM_PATH"; then
+            error "Couldn't download photon kernel source rpm"
+        fi
+    fi
+
+    install_kernel_dependencies "$KERNEL_SRC_RPM_PATH"
+
+
+}
+
+create_macro_file() {
+    local linux_version
+    [[ "$KERNEL_FLAVOR" == "generic" ]] && linux_version="$VERSION_RELEASE_FLAVOR" || linux_version="${VERSION_RELEASE_FLAVOR}-${KERNEL_FLAVOR}"
+
+    local macrofile="$TEMP_DIR/rpmbuild/macros"
+    echo "%define RPM_NAME $RPM_NAME" > $macrofile
+    echo "%define dist .$PH_TAG" >> $macrofile
+    echo "%define RPM_VERSION $RPM_VERSION" >> $macrofile
+    echo "%define RPM_RELEASE $RPM_RELEASE" >> $macrofile
+    echo "%define LINUX_VERSION $linux_version" >> $macrofile
+    echo "%define KERNEL_SRC_RPM $KERNEL_SRC_RPM" >> $macrofile
+    echo "%define LIVEPATCH_NAME $LIVEPATCH_NAME" >> $macrofile
+    if [[ -n "$SIGNC" ]]; then
+        echo "%define signing_script $signc" >> $macrofile
+        echo "%define signing_user $signc_uname" >> $macrofile
+    fi
+
+    # For 3.0 kernels, default to using the -R flag since klp_replace is not supported.
+    # For all other kernels, use the value specified by the user (if any).
+    if [[ $NON_REPLACE_FLAG -eq 1 || $PHOTON_VERSION == "3.0" ]]; then
+        echo "%define NON_REPLACE_FLAG -R" >> $macrofile
+    else
+        echo "%define NON_REPLACE_FLAG %{nil}" >> $macrofile
+    fi
+
+    if [[ $EXPORT_DEBUGINFO -eq 1 ]]; then
+        echo "%define SKIP_CLEANUP --skip-cleanup" >> $macrofile
+    else
+        echo "%define SKIP_CLEANUP %{nil}" >> $macrofile
+    fi
+
+    #Copy patches and description files to sources directory
+    cp "${patches[@]}" "$TEMP_DIR"/rpmbuild/SOURCES || error
+    local sources_file="$TEMP_DIR"/rpmbuild/SOURCES/sources.inc
+    >"$sources_file"
+
+    local s_cnt=101
+    echo -n "%define RPM_DESCRIPTION " >> $macrofile
+    if [ -f "$RPM_DESCFILE" ]; then
+        cp "$RPM_DESCFILE" "$TEMP_DIR"/rpmbuild/SOURCES
+        echo "Source${s_cnt}: $(basename "$RPM_DESCFILE")" >>  "$sources_file"
+        echo "%{expand:%(cat %{SOURCE${s_cnt}})}" >> $macrofile
+        ((s_cnt++))
+    else
+        echo "Livepatch module for Linux $linux_version" >> $macrofile
+    fi
+
+    echo -n "%define PATCHES " >> $macrofile
+    for patch in "${patches[@]}"; do
+        echo "Source${s_cnt}: $(basename "$patch")" >>  "$sources_file"
+        echo -n "%{SOURCE${s_cnt}} " >> $macrofile
+        ((s_cnt++))
+    done
+    echo >> $macrofile
+
+    if [[ -f "$DESC_FILE" ]]; then
+        cp "$DESC_FILE" "$TEMP_DIR"/rpmbuild/SOURCES
+        echo Source${s_cnt}: $(basename "$DESC_FILE") >>  "$sources_file"
+        echo "%define DESCRIPTION_FILE -D %{SOURCE${s_cnt}}" >> $macrofile
+        ((s_cnt++))
+    else
+        echo "%define DESCRIPTION_FILE %{nil}" >> $macrofile
     fi
 }
 
-#executes the kpatch-build command to build the livepatch
-kpatch_build() {
-    #only need -R flag for 3.0, since 3.0 doesn't support klp_replace
-    #otherwise leave it as set by the user
-    if [[ $PHOTON_VERSION == "3.0" ]]; then
-        NON_REPLACE_FLAG="-R"
-    fi
+# function to package the required module inside of an rpm
+build_and_package_kpatch_module() {
+    echo -e "\nPreparing to build livepatch"
+    local spec_file="$TEMP_DIR/rpmbuild/SPECS/livepatch.spec"
+    cp "$BUILD_RPM_SPECFILE" "$spec_file" || error
+    echo "* $(date "+%a %b %d %Y") Auto Livepatch $RPM_VERSION-$RPM_RELEASE" >> "$spec_file"
+    echo "- Auto Livepatch version $RPM_VERSION-$RPM_RELEASE built">> "$spec_file"
 
-    local skip_cleanup=""
-    if [[ $EXPORT_DEBUGINFO -eq 1 ]]; then
-        skip_cleanup="--skip-cleanup"
-    fi
+    create_macro_file
 
-    local description_file
-    [[ -f "$DESC_FILE" ]] && description_file="-D $DESC_FILE"
-    kpatch-build -v "$TEMP_DIR/$VMLINUX_PATH" \
-            -s "$TEMP_DIR/rpmbuild/BUILD/linux-$KERNEL_VERSION" \
-            -c "$TEMP_DIR/rpmbuild/BUILD/linux-$KERNEL_VERSION/.config" \
-            -j "$(nproc)" \
-            -n "$LIVEPATCH_NAME" \
-            -o "$OUTPUT_FOLDER" \
-            "${patches[@]}" \
-            $NON_REPLACE_FLAG \
-            $skip_cleanup \
-            $description_file \
-            || error "Building livepatch module failed."
+    if [[ $PACKAGE_AS_RPM -eq 1 ]]; then
+       rpmbuild -ba $spec_file --define "%_topdir $TEMP_DIR/rpmbuild" &> $GENLOGS_DIR/rpmbuild-livepatch-pkg.log
+    else
+       rpmbuild -bb $spec_file --define "%_topdir $TEMP_DIR/rpmbuild" &> $GENLOGS_DIR/rpmbuild-livepatch-pkg.log
+    fi
+    status=$?
+    [[ $DEBUG_LOGS -eq 1 || $status -ne 0 ]] && cat "$GENLOGS_DIR"/rpmbuild-livepatch-pkg.log
+    [[ $status -ne 0 ]] && error "Building and/or packaging kernel module as rpm failed"
     echo "Livepatch module successfully built"
+
+    if [ -n "$SIGNC" ]; then
+        echo "Signing RPM now."
+        find "$OUTPUT_FOLDER" -type f -name "*.rpm" -exec "$SIGNC" -t rpm -u "$SIGNC_UNAME" -a {} \; || error "Signing livepatch RPM failed!"
+    fi
+
     # save all of the debug info like vmlinux, changed objects, etc if asked to
     # vmlinux is the patched vmlinux, not original
     if [[ $EXPORT_DEBUGINFO -eq 1 ]]; then
         echo "Saving kpatch-build debug files to $DEBUGINFO_DIR"
 
         [[ -n "$DEBUGINFO_DIR" ]] && rm -rf "${DEBUGINFO_DIR:?}"/*  > /dev/null
-        mkdir -p $DEBUGINFO_DIR/patched-debuginfo
-        cp $RPM_BUILD_DIR/linux-"$KERNEL_VERSION"/vmlinux* \
-           $RPM_BUILD_DIR/linux-"$KERNEL_VERSION"/modules* \
-           $RPM_BUILD_DIR/linux-"$KERNEL_VERSION"/Module.symvers \
-           $DEBUGINFO_DIR/patched-debuginfo
+        mkdir -p "$DEBUGINFO_DIR"/patched-debuginfo
         cp -r ${HOME}/.kpatch/tmp "$DEBUGINFO_DIR"/kpatch-tmp
+        cp ${HOME}/.kpatch/src/vmlinux* \
+           ${HOME}/.kpatch/src/modules* \
+           ${HOME}/.kpatch/src/Module.symvers \
+           "$DEBUGINFO_DIR"/patched-debuginfo
     fi
-}
-
-
-# function to package the required module inside of an rpm
-package_module_in_rpm() {
-    echo -e "\nPreparing to build rpm"
-
-    local linux_version
-    [[ "$KERNEL_FLAVOR" == "generic" ]] && linux_version="$VERSION_RELEASE_FLAVOR" || linux_version="${VERSION_RELEASE_FLAVOR}-${KERNEL_FLAVOR}"
-
-    # set up temporary rpm build environment
-    pushd "$TEMP_DIR" > /dev/null || error
-    local rpmdir="%_topdir %(echo $PWD)/rpmbuild"
-    mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} || error
-    popd > /dev/null || error
-
-    cp "$OUTPUT_FOLDER"/"$LIVEPATCH_NAME".ko "$TEMP_DIR"/rpmbuild/SOURCES || error
-
-    local signc_args=()
-    [[ -n "$SIGNC" ]] && signc_args+=(
-        --define "%signing_script %(echo $SIGNC)"
-        --define "%signing_user %(echo $SIGNC_UNAME)"
-    )
-
-    # fill in needed info in spec file skeleton
-    local spec_file="$TEMP_DIR/rpmbuild/SPECS/livepatch.spec"
-    cp "$BUILD_RPM_SPECFILE" "$spec_file" || error
-    sed -i "s/@@VERSION@@/$RPM_VERSION/g" "$spec_file" || error "Filling in RPM vesion for spec file skeleton failed"
-    sed -i "s/@@RELEASE@@/$RPM_RELEASE/g" "$spec_file" || error "Filling in RPM release for  spec file skeleton failed"
-    sed -i "s/@@LIVEPATCH_NAME@@/$LIVEPATCH_NAME/g" "$spec_file" || error "Filling in livepatch name for spec file skeleton failed"
-    sed -i "s/@@RPM_NAME@@/$RPM_NAME/g" "$spec_file" || error "Filling in RPM name for spec file skeleton failed"
-    sed -i "s/@@LINUX_VERSION@@/$linux_version/g" "$spec_file" || error "Filling in linux version for spec file skeleton failed"
-
-    if [ -f "$RPM_DESCFILE" ]; then
-        awk -v desc="$(< "$RPM_DESCFILE")" '{gsub(/@@DESCRIPTION@@/, desc)}1' "$spec_file" > "$spec_file".tmp ||
-        error "Filling in description for spec file skeleton failed"
-        mv -f "$spec_file".tmp "$spec_file"
-    else
-        sed -i "s/@@DESCRIPTION@@/Livepatch module for Linux $linux_version\n/g" "$spec_file" || 
-        error "Filling in description for spec file skeleton failed"
-    fi
-    echo "* $(date "+%a %b %d %Y") Auto Livepatch $RPM_VERSION-$RPM_RELEASE" >> "$spec_file"
-    echo "- Auto Livepatch version $RPM_VERSION-$RPM_RELEASE built">> "$spec_file"
-    echo "Building rpm"
-    rpmbuild -ba $spec_file "${signc_args[@]}" --define "$rpmdir" --define "%dist .$PH_TAG" &> $GENLOGS_DIR/rpmbuild-livepatch-pkg.log
-    status=$?
-    [[ $DEBUG_LOGS -eq 1 ]] && cat "$GENLOGS_DIR"/rpmbuild-livepatch-pkg.log
-    [[ $status -ne 0 ]] && error "Packaging kernel module as rpm failed"
 
     # should only build for x86_64 arch but put a * there just in case
-    cp "$TEMP_DIR"/rpmbuild/RPMS/*/"$RPM_NAME"*.rpm "$OUTPUT_FOLDER" || error "Current dir: $(pwd). Failed to save RPM to $OUTPUT_FOLDER"
-
+    if [[ $PACKAGE_AS_RPM -eq 1 ]]; then
+        cp "$TEMP_DIR"/rpmbuild/RPMS/*/"$RPM_NAME"*.rpm "$OUTPUT_FOLDER" || error "Current dir: $(pwd). Failed to save RPMs to $OUTPUT_FOLDER"
+        cp "$TEMP_DIR"/rpmbuild/SRPMS/"$RPM_NAME"*.rpm "$OUTPUT_FOLDER" || error "Current dir: $(pwd). Failed to save source RPM to $OUTPUT_FOLDER"
+    fi
+    cp "$TEMP_DIR"/rpmbuild/BUILD/"$LIVEPATCH_NAME".ko "$OUTPUT_FOLDER"  || error "Current dir: $(pwd). Failed to save ko file to $OUTPUT_FOLDER"
     echo "SUCCESS: Building rpm finished"
 
-    if [ -n "$SIGNC" ]; then
-        echo "Signing RPM now."
-        find "$OUTPUT_FOLDER" -type f -name "*.rpm" -exec "$SIGNC" -t rpm -u "$SIGNC_UNAME" -a {} \; || error "Signing livepatch RPM failed!"
-    fi
 }
 
 cleanup() {
@@ -492,32 +495,31 @@ cleanup() {
 #cleanup on exit
 trap cleanup EXIT SIGINT SIGTERM
 
-#make sure our working directory is clean before we start
+#make sure our working directories are clean before we start
 rm -rf "$TEMP_DIR"
 rm -rf "$GENLOGS_DIR"
+rm -rf ${HOME}/.kpatch/
 
 #parse command line arguments
 parse_args "$@"
 
 mkdir -p "$TEMP_DIR"
+mkdir -p "$TEMP_DIR"/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} || error
 
 #set variables for all filenames/paths
 set_kernel_package_paths
 
 print_config
 
-
 pushd $TEMP_DIR > /dev/null || error
-extract_source_rpm
 #download and extract vmlinux
 parse_debuginfo_rpm
+
 gcc_version_check "$VMLINUX_PATH"
+
+download_source_rpm
 popd > /dev/null
 
-echo -e "\nAll sources ready, building livepatch module."
+echo -e "\nAll ready, building livepatch module."
 echo -e "This may take up to one hour\n"
-kpatch_build
-
-if [[ $PACKAGE_AS_RPM -eq 1 ]]; then
-    package_module_in_rpm
-fi
+build_and_package_kpatch_module
diff --git a/SPECS/kpatch/utils/rpm/livepatch_spec.template b/SPECS/kpatch/utils/rpm/livepatch_spec.template
--- a/SPECS/kpatch/utils/rpm/livepatch_spec.template
+++ b/SPECS/kpatch/utils/rpm/livepatch_spec.template
@@ -1,15 +1,16 @@
-Name:           @@RPM_NAME@@
-Version:        @@VERSION@@
-Release:        @@RELEASE@@%{?dist}
+%include        %{_topdir}/macros
+Name:           %{RPM_NAME}
+Version:        %{RPM_VERSION}
+Release:        %{RPM_RELEASE}%{?dist}
 Vendor:         VMware, Inc.
 Group:          System Environment/Kernel
 License:        GPLv2
 Summary:        Package containing a livepatch module for Photon OS
 Distribution:   Photon
 
-Requires: kpatch >= 0.9.10-1
+Requires:       kpatch >= 0.9.10-1
 
-%define _modulesdir /lib/modules/@@LINUX_VERSION@@
+%define _modulesdir /lib/modules/%{LINUX_VERSION}
 %define __modules_install_post \
     if [ -n "%{?signing_script}" ]; then \
         find %{buildroot}%{_modulesdir} -type f -name "*.ko" -print0 \\\
@@ -25,33 +26,62 @@ Requires: kpatch >= 0.9.10-1
     %{__modules_install_post}\
 %{nil}
 
-%description
-@@DESCRIPTION@@
+Source0:        vmlinux-%{LINUX_VERSION}
+Source1:        %{KERNEL_SRC_RPM}
+Source2:        sources.inc
+%include        %{SOURCE2}
 
+%description
+%{RPM_DESCRIPTION}
+
+%build
+kpatch-build -v %{SOURCE0} \
+            -r %{SOURCE1} \
+            -j "$(nproc)" \
+            -n %{LIVEPATCH_NAME} \
+            %{NON_REPLACE_FLAG} \
+            %{SKIP_CLEANUP} \
+            %{DESCRIPTION_FILE} \
+            %{PATCHES}
+
+if [ -n "$SIGNC" ]; then
+    echo "Signing RPM now."
+    find "$OUTPUT_FOLDER" -type f -name "*.rpm" -exec "$SIGNC" -t rpm -u "$SIGNC_UNAME" -a {} \; || error "Signing livepatch RPM failed!"
+fi
 
 %install
-mkdir -p %{buildroot}%{_modulesdir}/extra/livepatches/
-cp ../SOURCES/@@LIVEPATCH_NAME@@.ko %{buildroot}%{_modulesdir}/extra/livepatches/
+install -d %{buildroot}%{_modulesdir}/extra/livepatches/
+install -D -m 744  %{LIVEPATCH_NAME}.ko %{buildroot}%{_modulesdir}/extra/livepatches/
+
+%debug_package
 
 %pre
-echo "Required linux version is: @@LINUX_VERSION@@, current version is $(uname -r)"
-if [[ @@LINUX_VERSION@@ != $(uname -r) ]]; then
+echo "Required linux version is %{LINUX_VERSION}, current version is $(uname -r)"
+if [[ %{LINUX_VERSION} != $(uname -r) ]]; then
     echo "ABORT: Looks like you have the wrong linux version installed. This package is compatible only with @@LINUX_VERSION@@"
     exit 1
 fi
 
 %postun
 # uninstall and unload livepatch module
-kpatch uninstall @@LIVEPATCH_NAME@@ || echo "kpatch unload failed - maybe module was not loaded?"
+kpatch uninstall %{LIVEPATCH_NAME} || echo "kpatch unload failed - maybe module was not loaded?"
 
 %post
+set -e
+cleanup() {
+    echo "Cleaning up due to failure..." >&2
+    kpatch uninstall %{LIVEPATCH_NAME} || true
+    exit 1
+}
+trap cleanup ERR
+
 # load livepatch module
-kpatch install %{_modulesdir}/extra/livepatches/@@LIVEPATCH_NAME@@.ko
-kpatch load %{_modulesdir}/extra/livepatches/@@LIVEPATCH_NAME@@.ko
+kpatch install %{_modulesdir}/extra/livepatches/%{LIVEPATCH_NAME}.ko
+kpatch load %{_modulesdir}/extra/livepatches/%{LIVEPATCH_NAME}.ko
 depmod -a
 
 %files
 %defattr(-,root,root,-)
-%{_modulesdir}/extra/livepatches/@@LIVEPATCH_NAME@@.ko
+%{_modulesdir}/extra/livepatches/%{LIVEPATCH_NAME}.ko
 
 %changelog
