open-vm-tools: Update enable-custom-scripts logic in GOSC
DEFAULT-RUN-POST-CUST-SCRIPT is added to cust.cfg. Custom Scripts are
run based on the following conditions:
   1. If “enable-custom-script” is absent / not set, then
      1.1 If DEFAULT-RUN-POST-CUST-SCRIPT is yes, then run custom script.
      1.2 If DEFAULT-RUN-POST-CUST-SCRIPT is no or not set, then fail / abort Guest Customization.
   2. If “enable-custom-script” is explicitly set, then
      2.1 If “enable-custom-script” is set to true, then run custom script.
      2.2 If “enable-custom-script” is set to false, then fail / abort Guest Customization.

Change-Id: Ie8d71f6a626d190f651ddda60bd6c3abec597e10
Reviewed-on: http://photon-jenkins.eng.vmware.com:8082/9908
Tested-by: gerrit-photon <photon-checkins@vmware.com>
Reviewed-by: Shreenidhi Shedi <sshedi@vmware.com>
Reviewed-by: Keerthana K <keerthanak@vmware.com>

diff --git a/SPECS/open-vm-tools/gosc-force-run-cust-script.patch b/SPECS/open-vm-tools/gosc-force-run-cust-script.patch
--- a/SPECS/open-vm-tools/gosc-force-run-cust-script.patch
+++ b/SPECS/open-vm-tools/gosc-force-run-cust-script.patch
@@ -1,17 +1,20 @@
-commit ed208b2cce5583ad860e9f37a0c565cc7859f424
+commit f190f6f06deb455ce73166b7a8810dc56bba1b88
 Author: Keerthana K <keerthanak@vmware.com>
-Date:   Mon Jun 8 17:34:37 2020 +0530
+Date:   Fri Jun 19 12:55:56 2020 +0530
 
-    custom script: Add FORCE-RUN-POST-CUST-SCRIPT
-    
-    FORCE-RUN-POST-CUST-SCRIPT is added to cust.cfg. Custom Scripts are
-    run based on this flag (0/1/not set).
-    1. If FORCE-RUN-POST-CUST-SCRIPT is yes in cust.cfg, we don't read enable-custom-scripts value. Run custom script.
-    2. If FORCE-RUN-POST-CUST-SCRIPT is no / not exist in cust.cfg, enable-custom-scripts is true, run custom script.
-    3. If FORCE-RUN-POST-CUST-SCRIPT is no / not exist in cust.cfg, enable-custom-scripts is false / not set, report error and abort the guest customization.
+    custom script: Add DEFAULT-RUN-POST-CUST-SCRIPT
+
+    DEFAULT-RUN-POST-CUST-SCRIPT is added to cust.cfg. Custom Scripts are
+    run based on the following conditions:
+       1. If “enable-custom-script” is absent / not set, then
+          1.1 If DEFAULT-RUN-POST-CUST-SCRIPT is yes, then run custom script.
+          1.2 If DEFAULT-RUN-POST-CUST-SCRIPT is no or not set, then fail / abort Guest Customization.
+       2. If “enable-custom-script” is explicitly set, then
+          2.1 If “enable-custom-script” is set to true, then run custom script.
+          2.2 If “enable-custom-script” is set to false, then fail / abort Guest Customization.
 
 diff --git gosc-scripts/imc-shell/imgcust-scripts/ConfigFile.sh gosc-scripts-modify/imc-shell/imgcust-scripts/ConfigFile.sh
-index 1d6e064..884980e 100755
+index 1d6e064..f773d2f 100755
 --- gosc-scripts/imc-shell/imgcust-scripts/ConfigFile.sh
 +++ gosc-scripts-modify/imc-shell/imgcust-scripts/ConfigFile.sh
 @@ -1400,3 +1400,19 @@ ConfigFile_GetPrimaryNic()
@@ -30,40 +33,60 @@ index 1d6e064..884980e 100755
 +{
 +  local val='' # has to be declared before assigned
 +
-+  val=$(ConfigFile_GetOptionalBoolean 'MISC|FORCE-RUN-POST-CUST-SCRIPT') || exit 1
++  val=$(ConfigFile_GetOptionalBoolean 'MISC|DEFAULT-RUN-POST-CUST-SCRIPT') || exit 1
 +
 +  echo "$val"
 +}
+diff --git gosc-scripts/imc-shell/imgcust-scripts/CustomizationUtils.sh gosc-scripts-modify/imc-shell/imgcust-scripts/CustomizationUtils.sh
+index a851d88..0f3d052 100755
+--- gosc-scripts/imc-shell/imgcust-scripts/CustomizationUtils.sh
++++ gosc-scripts-modify/imc-shell/imgcust-scripts/CustomizationUtils.sh
+@@ -1305,8 +1305,10 @@ GetToolsConfig() {
+       IFS=' ' read -r -a array <<< "$result"
+       if echo "${array[3]}" | grep -iqwF "true"; then
+          echo "${array[3]}"
++      elif echo "${array[3]}" | grep -iqwF "false"; then
++         echo "${array[3]}"
+       else
+-         echo "false"
++         echo "not set"
+       fi
+    else
+       echo "false"
 diff --git gosc-scripts/imc-shell/imgcust-scripts/PhotonCustomization.sh gosc-scripts-modify/imc-shell/imgcust-scripts/PhotonCustomization.sh
-index 10d8795..0e61e68 100755
+index 10d8795..822df82 100755
 --- gosc-scripts/imc-shell/imgcust-scripts/PhotonCustomization.sh
 +++ gosc-scripts-modify/imc-shell/imgcust-scripts/PhotonCustomization.sh
-@@ -13,16 +13,22 @@ RunCloudConfig()
+@@ -12,15 +12,28 @@ RunCloudConfig()
+ 
    ConfigFile_LoadConfigFile $configPath
  
-   #Check whether post custom script is present and the file is non empty then
+-  #Check whether post custom script is present and the file is non empty then
 -  #Read enable-custom-scripts value from /etc/vmware-tools/tools.conf through vmware-toolbox-cmd command
 -  #If enable-custom-scripts value is false then cancel the guest customization and Report failure.
-+  #Check whether FORCE-RUN-POST-CUST-SCRIPT is set or not, and run post custom script only on following conditions:
-+    #  If FORCE-RUN-POST-CUST-SCRIPT is yes in cust.cfg, then don't read enable-custom-scripts value. Run custom script.
-+    #  If FORCE-RUN-POST-CUST-SCRIPT is no / not exist in cust.cfg, and enable-custom-scripts is true, run custom script.
-+    #  If FORCE-RUN-POST-CUST-SCRIPT is no / not exist in cust.cfg, enable-custom-scripts is false / not set, report error and abort the guest customization.
++  # Check whether post custom script is present and the file is non empty then
++  # Check "enable-custom-script" value from VM Tools configuration:
++       # If "enable-custom-script" is absent / not set, then
++           # If DEFAULT-RUN-POST-CUST-SCRIPT is yes, then run custom script.
++           # If DEFAULT-RUN-POST-CUST-SCRIPT is no or not set, then report error and abort the guest customization.
++       # If "enable-custom-script" is explicitly set, then enable/disable the post script per "enable-custom-scripts" value.
++           # If “enable-custom-script” is set to true, then run custom script.
++           # If “enable-custom-script” is set to false, then report error and abort the guest customization.
++
    local postScript=$(ConfigFile_GetCustomScriptName)
    if [[ -n "$postScript" ]]; then
       postScript=`${DIRNAME} $configFilePath`"/$postScript"
       if [[ -f "$postScript" && -s "$postScript" ]]; then
--        local value=$(GetToolsConfig "deployPkg" "enable-custom-scripts")
+         local value=$(GetToolsConfig "deployPkg" "enable-custom-scripts")
 -        if !(echo $value | grep -iqwF "true"); then
--           PostDeployPkgStatus "enable-custom-scripts is set to false"
--           Die "enable-custom-scripts is set to false. Failing customization"
-+        local forceCustomScript=$(ConfigFile_GetForceRunPostCustScript)
-+        Debug "FORCE-RUN-POST-CUST-SCRIPT: [$forceCustomScript]"
-+        if [[ -z "$forceCustomScript" || $forceCustomScript == 0 ]]; then
-+           local value=$(GetToolsConfig "deployPkg" "enable-custom-scripts")
-+           if !(echo $value | grep -iqwF "true"); then
-+              PostDeployPkgStatus "enable-custom-scripts is set to false"
-+              Die "enable-custom-scripts is set to false. Failing customization"
++        if (echo $value | grep -iqwF "not set"); then
++           local forceCustomScript=$(ConfigFile_GetForceRunPostCustScript)
++           Debug "DEFAULT-RUN-POST-CUST-SCRIPT: [$forceCustomScript]"
++           if [[ -z "$forceCustomScript" || $forceCustomScript == 0 ]]; then
++              PostDeployPkgStatus "enable-custom-scripts is not set and DEFAULT-RUN-POST-CUST-SCRIPT is no or not set"
++              Die "enable-custom-scripts is not set and DEFAULT-RUN-POST-CUST-SCRIPT is no or not set. Failing customization"
 +           fi
++        elif (echo $value | grep -iqwF "false"); then
+            PostDeployPkgStatus "enable-custom-scripts is set to false"
+            Die "enable-custom-scripts is set to false. Failing customization"
          fi
-      fi
-   fi
